### ISSUE TITLE
Getting and setting parameters for dynamic response

### ISSUE THREAD

**Issue by Inalvis** [sibyjackgrove/SolarPV-DER-simulation-utility#1]
**Is your feature request related to a problem? Please describe.**
No, problem is related to having freedom of getting and setting parameters of the ODE's for dynamic simulation

**Describe the solution you'd like**
Provide setting and getting methods for the parameters of the dynamic equations such as inverter output currents, controller dynamics, base values and parameter, etc.

**Comment by sibyjackgrove** [comment]
@Inalvis Thank you for opening the first issue for this repository and the feature request. 

I will add a method to set parameters for the following components in the model: PV module, inverter ratings, circuit elements, and controller gains. You can expect an update in the next couple of days. A few clarifications follow regarding getting the parameters.

It is possible to get the parameter values using the python object. For e.g. if you want the value of the inverter circuit parameters, you can use: 
`PVDER_object.C_actual  #Lf_actual`  

If you want to print all the parameters for a particular component at once, you can use:
`PVDER_object.show_PV_DER_parameters(quantity='inverter_ratings') #'circuit_parameters', 'controller_gains'`
For inverter current/voltage at the end of the simulation (current state), you can access them using:  
`PVDER_object.Irms #Vrms, Vtrms`

If you want the inverter current/voltage for the full length of the simulation, you can access them using:

`sim_object.Irms_t #Vrms_t, Vtrms_t`

I can also add a method to return the DER parameters and the voltage, current quantities as a Python dictionary. Is that what you what?

**Comment by Inalvis** [comment]
@sibyjackgrove 
the "show_PV_DER_parameter" prints the parameters we need but it does not allow to extract the values and store them. I tried storing the string that is outputted but was unsuccessful.  
What you suggested of adding a method to return the values will be very useful. Could this be applied to the parameters such as the inverter ratings and controller gains?

Thank you for the other functions, they are very useful.

**Comment by sibyjackgrove** [comment]
@Inalvis I have added requested features with commits 8227435733eb2f66698c19b219b5f277eb109e35, 265536631c57c0d960687891c030396db0603dc8, and 40dde5a2a27a2efd2b5c709bdc1411abce6ecd68.

Please refer to https://github.com/sibyjackgrove/SolarPV-DER-simulation-utility/blob/master/examples/PV-DER_parameter_update_example.ipynb for usage examples.

Closing this issue, please free free to reopen if you run into errors.
