### ISSUE TITLE
Manual needs to be updated

### ISSUE THREAD

**Issue by faezahafiz** [sibyjackgrove/SolarPV-DER-simulation-utility#3]
Please provide a manual for each function of each object. Suppose I want to activate LVRT trip. I don't know which command I need to type to activate it. I needed to go through the code and find it out (obj.LVRT_TRIP= True). So, users are not getting clear idea about the capability of the model. Also please provide the default values in the manual to make it user friendly.

**Comment by sibyjackgrove** [comment]
Thank you @faezahafiz for opening the issue. I will provide a document describing the flags.

**Comment by sibyjackgrove** [comment]
Additional [documentation](https://github.com/sibyjackgrove/SolarPV-DER-simulation-utility/blob/master/docs/PVDER_flags_variables_methods.md) was added with 1c4e7f4. Closing issue. Please feel free to reopen if additional information is required.
